# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2026 0702hjj

"""On-demand IFC materialization for historical big versions (spec §5.5, I5).

Only the latest big version keeps a materialized IFC under ``versions/``;
older snapshots are rebuildable cache, regenerated by sandbox-running their
script (``scripts/v{n}.py`` — the source of truth) into
``models/{id}/ifc_cache/v{n}.ifc``. The cache is a rebuild accelerator, not
state: entries are evicted LRU (oldest mtime first) past ``IFC_CACHE_MAX``
and can always be regenerated.

Determinism caveat: rebuilt bytes differ from the original snapshot (IFC
header timestamps); only semantic equality holds (uuid5 GlobalIds), so
consumers must compare via ``diffing.compute_diff``, never byte equality.
"""

from __future__ import annotations

import os
from typing import Optional

from . import script_runner, script_versions, versions
from .config import Settings

IFC_CACHE_MAX = 4


def ifc_cache_dir(data_dir: str, model_id: str) -> str:
    return os.path.join(data_dir, "models", model_id, "ifc_cache")


def _evict_cache(cache_dir: str) -> None:
    """Keep at most IFC_CACHE_MAX v{n}.ifc files, evicting oldest by mtime."""
    entries = [
        name
        for name in os.listdir(cache_dir)
        if versions.VERSION_FILE_RE.match(name)
    ]
    if len(entries) <= IFC_CACHE_MAX:
        return
    entries.sort(key=lambda name: os.path.getmtime(os.path.join(cache_dir, name)))
    for name in entries[: len(entries) - IFC_CACHE_MAX]:
        os.remove(os.path.join(cache_dir, name))
        sidecar = os.path.join(cache_dir, name + ".map.json")
        if os.path.exists(sidecar):
            os.remove(sidecar)


def materialize_version(
    data_dir: str, model_id: str, version: str, settings: Settings
) -> str:
    """Return an IFC path for a big version, rebuilding from script if needed.

    Order: existing ``versions/v{n}.ifc`` snapshot → existing cache entry →
    sandbox re-run of ``scripts/v{n}.py`` into the cache. Raises
    FileNotFoundError when neither snapshot nor script exists; the sandbox
    run's HTTPException(422) propagates when the rebuild itself fails.
    """
    snapshot = versions.version_path(data_dir, model_id, version)
    if snapshot is not None:
        return snapshot
    script = script_versions.script_path(data_dir, model_id, version)
    if script is None:
        raise FileNotFoundError(f"no snapshot or script for version: {version}")

    cache_dir = ifc_cache_dir(data_dir, model_id)
    cached: Optional[str] = os.path.join(cache_dir, f"{version}.ifc")
    if os.path.isfile(cached):
        os.utime(cached)  # LRU：命中刷新 mtime
        return cached

    os.makedirs(cache_dir, exist_ok=True)
    with open(script, "r", encoding="utf-8") as fh:
        script_text = fh.read()
    script_runner.run_script(settings, script_text, cached, map_out=None)
    _evict_cache(cache_dir)
    return cached
